CREATE DATABASE [QuanLyDatBan]
GO

ALTER DATABASE [QuanLyDatBan] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [QuanLyDatBan].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [QuanLyDatBan] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyDatBan] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyDatBan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET CURSOR_DEFAULT GLOBAL 
GO
ALTER DATABASE [QuanLyDatBan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET DISABLE_BROKER 
GO
ALTER DATABASE [QuanLyDatBan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanLyDatBan] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuanLyDatBan] SET MULTI_USER 
GO
ALTER DATABASE [QuanLyDatBan] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanLyDatBan] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanLyDatBan] SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF) 
GO
ALTER DATABASE [QuanLyDatBan] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

USE [QuanLyDatBan]
GO

/****** Object:  Table [dbo].[Ban]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ban](
    [maBan] [nchar](10) NOT NULL,
	[maLoai] [nchar](10) NOT NULL,
	[trangThaiBan] [nvarchar](50) NOT NULL,
	[soLuongGhe] [int] NULL,
	[viTri] [nvarchar](50) NULL,
    CONSTRAINT [PK_Ban] PRIMARY KEY CLUSTERED 
    (
        [maBan] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[CaLamViec]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CaLamViec](
    [maCa] [nchar](10) NOT NULL,
	[maNV] [nvarchar](50) NOT NULL,
	[gioBatDau] [datetime] NOT NULL,
	[gioKetThuc] [datetime] NOT NULL,
    CONSTRAINT [PK_CaLamViec] PRIMARY KEY CLUSTERED 
    (
        [maCa] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[ChiTietDonDatBan]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietDonDatBan](
    [maHD] [nchar](20) NOT NULL,
	[maKH] [nchar](10) NOT NULL,
	[maNV] [nvarchar](50) NOT NULL,
	[maBan] [nchar](10) NOT NULL,
	[maYeuCau] [int] NOT NULL,
	[thoiGianTao] [datetime] NOT NULL,
	[ngayDatBan] [datetime] NOT NULL
    CONSTRAINT [PK_ChiTietDonDatBan] PRIMARY KEY CLUSTERED 
    (
        [maHD] ASC,
        [maYeuCau] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DonDatBan]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonDatBan](
    [maHD] [nchar](20) NOT NULL,
	[soLuongKhach] [int] NOT NULL,
    CONSTRAINT [PK_DonDatBan] PRIMARY KEY CLUSTERED 
    (
        [maHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[KhachHang]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KhachHang](
	[maKH] [nchar](10) NOT NULL,
	[tenKH] [nvarchar](50) NOT NULL,
	[sdt] [nchar](11) NULL,
	[email] [nvarchar](50) NULL,
	[lichSuDatBan] [nvarchar](max) NULL,
    CONSTRAINT [PK_KhachHang] PRIMARY KEY CLUSTERED 
    (
        [maKH] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[LoaiBan]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoaiBan](
    [maLoai] [nchar](10) NOT NULL,
	[tenLoai] [nvarchar](50) NOT NULL,
    CONSTRAINT [PK_LoaiBan] PRIMARY KEY CLUSTERED 
    (
        [maLoai] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[MonAn]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MonAn](
   [maMonAn] [nchar](10) NOT NULL,
	[tenMonAn] [nvarchar](50) NOT NULL,
	[giaTien] [real] NOT NULL,
	[thongTinMon] [nvarchar](max) NULL,
	[trangThaiMonAn] [nvarchar](25) NOT NULL,
    CONSTRAINT [PK_MonAn] PRIMARY KEY CLUSTERED 
    (
        [maMonAn] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[NhanVien](
	[maNV] [nvarchar](50) NOT NULL,
	[maTK] [nchar](10) NOT NULL,
	[tenNV] [nvarchar](50) NOT NULL,
	[sdt] [nchar](11) NULL,
	[email] [nvarchar](50) NULL,
	[ngayVaoLam] [datetime] NOT NULL,
 CONSTRAINT [PK_NhanVien] PRIMARY KEY CLUSTERED 
(
	[maNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TaiKhoan]    Script Date: 10/18/2024 10:55:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaiKhoan](
	[maTK] [nchar](10) NOT NULL,
	[tenTK] [nvarchar](50) NOT NULL,
	[chucVu] [nchar](10) NOT NULL,
	[matKhau] [nchar](10) NOT NULL,
 CONSTRAINT [PK_TaiKhoan] PRIMARY KEY CLUSTERED 
(
	[maTK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE LoaiMon (
    maLoai nchar(10) PRIMARY KEY,
    tenLoai nvarchar(100) NOT NULL
);
GO
ALTER TABLE MonAn
ADD maLoai nchar(10);

-- Thiết lập khóa ngoại từ `MonAn` đến `LoaiMon`
ALTER TABLE MonAn
ADD CONSTRAINT FK_MonAn_LoaiMon FOREIGN KEY (maLoai) REFERENCES LoaiMon(maLoai);
GO
CREATE TABLE [dbo].[YeuCauKhachHang](
	[maYeuCau] [int] NOT NULL,
	[maMonAn] [nchar](10) NOT NULL,
	[maKH] [nchar](10) NOT NULL,
	[yeuCauDacBiet] [nvarchar](max) NULL,
	[danhSachMon] [nvarchar](max) NULL,
 CONSTRAINT [PK_YeuCauKhachHang] PRIMARY KEY CLUSTERED 
(
	[maYeuCau] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[Ban]  WITH CHECK ADD FOREIGN KEY([maLoai])
REFERENCES [dbo].[LoaiBan] ([maLoai])
GO
ALTER TABLE [dbo].[Ban]  WITH CHECK ADD FOREIGN KEY([maLoai])
REFERENCES [dbo].[LoaiBan] ([maLoai])
GO
ALTER TABLE [dbo].[CaLamViec]  WITH CHECK ADD FOREIGN KEY([maNV])
REFERENCES [dbo].[NhanVien] ([maNV])
GO
ALTER TABLE [dbo].[ChiTietDonDatBan]  WITH CHECK ADD FOREIGN KEY([maBan])
REFERENCES [dbo].[Ban] ([maBan])
GO
ALTER TABLE [dbo].[ChiTietDonDatBan]  WITH CHECK ADD FOREIGN KEY([maYeuCau])
REFERENCES [dbo].[YeuCauKhachHang] ([maYeuCau])
GO
ALTER TABLE [dbo].[ChiTietDonDatBan]  WITH CHECK ADD FOREIGN KEY([maHD])
REFERENCES [dbo].[DonDatBan] ([maHD])
GO
ALTER TABLE [dbo].[ChiTietDonDatBan]  WITH CHECK ADD FOREIGN KEY([maNV])
REFERENCES [dbo].[NhanVien] ([maNV])
GO
ALTER TABLE [dbo].[NhanVien]  WITH CHECK ADD FOREIGN KEY([maTK])
REFERENCES [dbo].[TaiKhoan] ([maTK])
GO
ALTER TABLE [dbo].[YeuCauKhachHang]  WITH CHECK ADD FOREIGN KEY([maMonAn])
REFERENCES [dbo].[MonAn] ([maMonAn])
GO
ALTER TABLE [dbo].[YeuCauKhachHang]  WITH CHECK ADD FOREIGN KEY([maKH])
REFERENCES [dbo].[KhachHang] ([maKH])
GO
USE [master]
GO
ALTER DATABASE [QuanLyDatBan] SET  READ_WRITE 
GO