/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Admin
 */
public class DatBan extends javax.swing.JFrame {

    /**
     * Creates new form DatBan
     */
    public DatBan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_DonDat = new javax.swing.JPanel();
        P_HoaDon = new javax.swing.JPanel();
        P_TongTien = new javax.swing.JPanel();
        L_tongTien = new javax.swing.JLabel();
        lt_tongtien = new javax.swing.JLabel();
        L_thue = new javax.swing.JLabel();
        lt_tax = new javax.swing.JLabel();
        scrolltable = new javax.swing.JScrollPane();
        T_hoaDon = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        L_nv = new javax.swing.JLabel();
        L_tenNV = new javax.swing.JLabel();
        L_kh = new javax.swing.JLabel();
        L_tenKH = new javax.swing.JLabel();
        button_bar = new javax.swing.JPanel();
        Btn_HuyBang = new javax.swing.JButton();
        Btn_LuuBang = new javax.swing.JButton();
        Btn_ChuyenBan = new javax.swing.JButton();
        Btn_GhepBan = new javax.swing.JButton();
        Btn_ChonBan = new javax.swing.JButton();
        Btn_ThemMon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P_DonDat.setBackground(new java.awt.Color(255, 255, 255));

        P_HoaDon.setBackground(new java.awt.Color(255, 255, 255));

        L_tongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_tongTien.setText("1000000");
        L_tongTien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L_tongTien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lt_tongtien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lt_tongtien.setText("Tổng Tiền");

        L_thue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_thue.setText("100000");
        L_thue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lt_tax.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lt_tax.setText("Thuế");

        javax.swing.GroupLayout P_TongTienLayout = new javax.swing.GroupLayout(P_TongTien);
        P_TongTien.setLayout(P_TongTienLayout);
        P_TongTienLayout.setHorizontalGroup(
            P_TongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_TongTienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lt_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_thue, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lt_tongtien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_TongTienLayout.setVerticalGroup(
            P_TongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_TongTienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_TongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(lt_tongtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lt_tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_thue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        scrolltable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                scrolltableComponentHidden(evt);
            }
        });

        T_hoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên món ăn", "số lượng", "Đơn giá", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrolltable.setViewportView(T_hoaDon);

        javax.swing.GroupLayout P_HoaDonLayout = new javax.swing.GroupLayout(P_HoaDon);
        P_HoaDon.setLayout(P_HoaDonLayout);
        P_HoaDonLayout.setHorizontalGroup(
            P_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_TongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrolltable, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        P_HoaDonLayout.setVerticalGroup(
            P_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_HoaDonLayout.createSequentialGroup()
                .addComponent(scrolltable, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        L_nv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_nv.setText("Nhân viên: ");

        L_tenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_tenNV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        L_tenNV.setVerifyInputWhenFocusTarget(false);

        L_kh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_kh.setText("Khách Hàng: ");

        L_tenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_tenKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        L_tenKH.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(L_kh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_nv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_kh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(L_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Btn_HuyBang.setBackground(new java.awt.Color(255, 102, 51));
        Btn_HuyBang.setForeground(new java.awt.Color(255, 255, 255));
        Btn_HuyBang.setText("Hủy");
        Btn_HuyBang.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Btn_HuyBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HuyBangActionPerformed(evt);
            }
        });

        Btn_LuuBang.setBackground(new java.awt.Color(153, 255, 153));
        Btn_LuuBang.setText("Lưu HD");
        Btn_LuuBang.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Btn_LuuBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LuuBangActionPerformed(evt);
            }
        });
        Btn_LuuBang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Btn_LuuBangKeyPressed(evt);
            }
        });

        Btn_ChuyenBan.setBackground(new java.awt.Color(255, 204, 255));
        Btn_ChuyenBan.setText("Chuyển Bàn");
        Btn_ChuyenBan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Btn_ChuyenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ChuyenBanActionPerformed(evt);
            }
        });

        Btn_GhepBan.setBackground(new java.awt.Color(204, 204, 255));
        Btn_GhepBan.setText("Ghép Bàn");
        Btn_GhepBan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Btn_GhepBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GhepBanActionPerformed(evt);
            }
        });

        Btn_ChonBan.setBackground(new java.awt.Color(153, 255, 255));
        Btn_ChonBan.setText("Chọn Bàn");
        Btn_ChonBan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Btn_ThemMon.setBackground(new java.awt.Color(255, 255, 204));
        Btn_ThemMon.setText("Thêm Món");
        Btn_ThemMon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout button_barLayout = new javax.swing.GroupLayout(button_bar);
        button_bar.setLayout(button_barLayout);
        button_barLayout.setHorizontalGroup(
            button_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_ChonBan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_ThemMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(Btn_GhepBan)
                .addGap(18, 18, 18)
                .addComponent(Btn_ChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_HuyBang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_LuuBang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        button_barLayout.setVerticalGroup(
            button_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_barLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(button_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_ChuyenBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_GhepBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Btn_ChonBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_ThemMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(button_barLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(button_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_LuuBang, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_HuyBang, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout P_DonDatLayout = new javax.swing.GroupLayout(P_DonDat);
        P_DonDat.setLayout(P_DonDatLayout);
        P_DonDatLayout.setHorizontalGroup(
            P_DonDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_DonDatLayout.setVerticalGroup(
            P_DonDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_DonDatLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_DonDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_DonDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_HuyBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HuyBangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_HuyBangActionPerformed

    private void Btn_LuuBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LuuBangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_LuuBangActionPerformed

    private void Btn_LuuBangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Btn_LuuBangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_LuuBangKeyPressed

    private void Btn_ChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChuyenBanActionPerformed
        // TODO add your handling code here:
        Form_Chuyen_GhepBan F_chuyenBan = new Form_Chuyen_GhepBan();
        F_chuyenBan.setVisible(true);
    }//GEN-LAST:event_Btn_ChuyenBanActionPerformed

    private void Btn_GhepBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GhepBanActionPerformed
        // TODO add your handling code here:
        Form_Chuyen_GhepBan F_ghepBan = new Form_Chuyen_GhepBan();
        F_ghepBan.setVisible(true);
    }//GEN-LAST:event_Btn_GhepBanActionPerformed

    private void scrolltableComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_scrolltableComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_scrolltableComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ChonBan;
    private javax.swing.JButton Btn_ChuyenBan;
    private javax.swing.JButton Btn_GhepBan;
    private javax.swing.JButton Btn_HuyBang;
    private javax.swing.JButton Btn_LuuBang;
    private javax.swing.JButton Btn_ThemMon;
    private javax.swing.JLabel L_kh;
    private javax.swing.JLabel L_nv;
    private javax.swing.JLabel L_tenKH;
    private javax.swing.JLabel L_tenNV;
    private javax.swing.JLabel L_thue;
    private javax.swing.JLabel L_tongTien;
    private javax.swing.JPanel P_DonDat;
    private javax.swing.JPanel P_HoaDon;
    private javax.swing.JPanel P_TongTien;
    private javax.swing.JTable T_hoaDon;
    private javax.swing.JPanel button_bar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lt_tax;
    private javax.swing.JLabel lt_tongtien;
    private javax.swing.JScrollPane scrolltable;
    // End of variables declaration//GEN-END:variables
}
