
package gui;


public class SignUp extends javax.swing.JFrame {

   
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DangKy = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        P_DangKy = new javax.swing.JPanel();
        L_DangKy = new javax.swing.JLabel();
        L_hoTen = new javax.swing.JLabel();
        T_hoTen = new javax.swing.JTextField();
        L_TaiKhoan = new javax.swing.JLabel();
        T_TaiKhoan = new javax.swing.JTextField();
        L_MatKhau = new javax.swing.JLabel();
        Btn_DangKy = new javax.swing.JButton();
        L_toDangNhap = new javax.swing.JLabel();
        Btn_DangNhap = new javax.swing.JButton();
        T_MatKhau = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SignUp");
        setPreferredSize(new java.awt.Dimension(800, 500));

        DangKy.setBackground(new java.awt.Color(255, 255, 255));
        DangKy.setPreferredSize(new java.awt.Dimension(800, 500));
        DangKy.setLayout(null);

        Logo.setBackground(new java.awt.Color(0, 102, 102));

        label_logo.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        label_logo.setForeground(new java.awt.Color(255, 255, 255));
        label_logo.setText("Thai Restaurant");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(label_logo)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        DangKy.add(Logo);
        Logo.setBounds(0, 0, 400, 500);

        P_DangKy.setBackground(new java.awt.Color(255, 255, 255));
        P_DangKy.setPreferredSize(new java.awt.Dimension(400, 500));

        L_DangKy.setBackground(new java.awt.Color(255, 255, 255));
        L_DangKy.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        L_DangKy.setForeground(new java.awt.Color(0, 102, 102));
        L_DangKy.setText("ĐĂNG KÝ");

        L_hoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_hoTen.setText("Họ Và Tên");

        T_hoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        L_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_TaiKhoan.setText("Tài Khoản");

        T_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        L_MatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L_MatKhau.setText("Mật Khẩu");

        Btn_DangKy.setBackground(new java.awt.Color(0, 102, 102));
        Btn_DangKy.setForeground(new java.awt.Color(255, 255, 255));
        Btn_DangKy.setText("Đăng Ký");
        Btn_DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DangKyActionPerformed(evt);
            }
        });

        L_toDangNhap.setText("Tôi đã có tài khoản.");

        Btn_DangNhap.setForeground(new java.awt.Color(255, 51, 51));
        Btn_DangNhap.setText("Đăng Nhập");
        Btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DangNhapActionPerformed(evt);
            }
        });

        T_MatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout P_DangKyLayout = new javax.swing.GroupLayout(P_DangKy);
        P_DangKy.setLayout(P_DangKyLayout);
        P_DangKyLayout.setHorizontalGroup(
            P_DangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_DangKyLayout.createSequentialGroup()
                .addGroup(P_DangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_DangKyLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(P_DangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_DangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(L_hoTen)
                                .addComponent(T_hoTen)
                                .addComponent(L_TaiKhoan)
                                .addComponent(T_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                .addComponent(L_MatKhau)
                                .addComponent(T_MatKhau))
                            .addComponent(Btn_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(P_DangKyLayout.createSequentialGroup()
                                .addComponent(L_toDangNhap)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_DangNhap))))
                    .addGroup(P_DangKyLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(L_DangKy)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        P_DangKyLayout.setVerticalGroup(
            P_DangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_DangKyLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(L_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L_hoTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L_TaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L_MatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_DangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_toDangNhap)
                    .addComponent(Btn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        DangKy.add(P_DangKy);
        P_DangKy.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DangKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DangKyActionPerformed

    private void Btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DangNhapActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Btn_DangNhapActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_DangKy;
    private javax.swing.JButton Btn_DangNhap;
    private javax.swing.JPanel DangKy;
    private javax.swing.JLabel L_DangKy;
    private javax.swing.JLabel L_MatKhau;
    private javax.swing.JLabel L_TaiKhoan;
    private javax.swing.JLabel L_hoTen;
    private javax.swing.JLabel L_toDangNhap;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel P_DangKy;
    private javax.swing.JTextField T_MatKhau;
    private javax.swing.JTextField T_TaiKhoan;
    private javax.swing.JTextField T_hoTen;
    private javax.swing.JLabel label_logo;
    // End of variables declaration//GEN-END:variables
}
